# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nexus.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'nexus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnexus.proto\x12\x05nexus\"2\n\x0bUserRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x15\n\rwalletAddress\x18\x02 \x01(\t\"/\n\x0bNodeRequest\x12\x10\n\x08nodeType\x18\x01 \x01(\x05\x12\x0e\n\x06userId\x18\x02 \x01(\t\"\x1e\n\x0cNodeResponse\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\"/\n\x0bTaskRequest\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\x12\x10\n\x08nodeType\x18\x02 \x01(\x05\"G\n\x0cTaskResponse\x12\x11\n\tprogramId\x18\x01 \x01(\t\x12\x14\n\x0cpublicInputs\x18\x02 \x01(\x0c\x12\x0e\n\x06taskId\x18\x03 \x01(\t\"\x94\x01\n\x11SubmitTaskRequest\x12\x0e\n\x06nodeId\x18\x01 \x01(\t\x12\x10\n\x08nodeType\x18\x02 \x01(\x05\x12\x11\n\tproofHash\x18\x03 \x01(\t\x12+\n\rnodeTelemetry\x18\x04 \x01(\x0b\x32\x14.nexus.NodeTelemetry\x12\r\n\x05proof\x18\x05 \x01(\x0c\x12\x0e\n\x06taskId\x18\x06 \x01(\t\"b\n\rNodeTelemetry\x12\x13\n\x0b\x66lopsPerSec\x18\x01 \x01(\x05\x12\x12\n\nmemoryUsed\x18\x02 \x01(\x05\x12\x16\n\x0ememoryCapacity\x18\x03 \x01(\x05\x12\x10\n\x08location\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nexus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=22
  _globals['_USERREQUEST']._serialized_end=72
  _globals['_NODEREQUEST']._serialized_start=74
  _globals['_NODEREQUEST']._serialized_end=121
  _globals['_NODERESPONSE']._serialized_start=123
  _globals['_NODERESPONSE']._serialized_end=153
  _globals['_TASKREQUEST']._serialized_start=155
  _globals['_TASKREQUEST']._serialized_end=202
  _globals['_TASKRESPONSE']._serialized_start=204
  _globals['_TASKRESPONSE']._serialized_end=275
  _globals['_SUBMITTASKREQUEST']._serialized_start=278
  _globals['_SUBMITTASKREQUEST']._serialized_end=426
  _globals['_NODETELEMETRY']._serialized_start=428
  _globals['_NODETELEMETRY']._serialized_end=526
# @@protoc_insertion_point(module_scope)
